### ISSUE TITLE
Release this repository into Rolling and other distros

### ISSUE THREAD

**Issue by ijnek** [ros-sports/vision_msgs_layers#10]
- [x] galactic (https://github.com/ros/rosdistro/pull/35098)
- [x] humble (https://github.com/ros/rosdistro/pull/35099)
- [x] rolling (https://github.com/ros/rosdistro/pull/35100)

**Comment by ijnek** [comment]
Requesting for release repository in https://github.com/ros2-gbp/ros2-gbp-github-org/issues/92

**Comment by ijnek** [comment]
Must branch off Humble.

**Comment by ijnek** [comment]
Closing once PRs for rosdistro are closed.

**Comment by jaagut** [comment]
I believe, this can now be closed
